/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package C_Frames;

import C_Conexion.Conexion;
import static C_Conexion.Conexion.con;
import java.awt.Component;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Blob;
import java.sql.Connection;
import static java.sql.JDBCType.BLOB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.sql.Types.BLOB;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static oracle.jdbc.OracleTypes.BLOB;
import oracle.sql.BLOB;

/**
 *
 * @author je_mg
 */
public class C_ADD_CP extends javax.swing.JFrame {
 Conexion erp;
String usuario;
    /**
     * Creates new form C_ADD_ES
     */
    public C_ADD_CP() {
        initComponents();
        erp=new Conexion();
        erp.OpenCon("ERP", "erp");
       
 

this.setLocationRelativeTo(null);
      

llenarComboPro();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpiarPerce = new javax.swing.JButton();
        btnAgregarPerce = new javax.swing.JButton();
        txfnombreC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxproveedor = new javax.swing.JComboBox();
        lblfoto = new javax.swing.JLabel();
        btnSeIm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGREGAR ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 43, 0))); // NOI18N

        btnLimpiarPerce.setBackground(new java.awt.Color(254, 254, 254));
        btnLimpiarPerce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-cancelar.png"))); // NOI18N
        btnLimpiarPerce.setToolTipText("");
        btnLimpiarPerce.setBorderPainted(false);
        btnLimpiarPerce.setContentAreaFilled(false);
        btnLimpiarPerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPerceActionPerformed(evt);
            }
        });

        btnAgregarPerce.setBackground(new java.awt.Color(254, 254, 254));
        btnAgregarPerce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        btnAgregarPerce.setBorderPainted(false);
        btnAgregarPerce.setContentAreaFilled(false);
        btnAgregarPerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPerceActionPerformed(evt);
            }
        });

        txfnombreC.setBackground(new java.awt.Color(254, 254, 254));
        txfnombreC.setForeground(new java.awt.Color(1, 1, 1));
        txfnombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfnombreCActionPerformed(evt);
            }
        });
        txfnombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfnombreCKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("Nombre imagen");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Seleccione un producto");

        cbxproveedor.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                cbxproveedorHierarchyChanged(evt);
            }
        });
        cbxproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxproveedorActionPerformed(evt);
            }
        });
        cbxproveedor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxproveedorPropertyChange(evt);
            }
        });
        cbxproveedor.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cbxproveedorVetoableChange(evt);
            }
        });

        lblfoto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "IMAGEN"));

        btnSeIm.setText("Seleciona imagen");
        btnSeIm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeImActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cbxproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txfnombreC, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimpiarPerce, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarPerce))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnSeIm)))
                .addGap(0, 194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfnombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeIm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarPerce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPerce, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarPerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPerceActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLimpiarPerceActionPerformed
   
    DefaultComboBoxModel modelocombo = new DefaultComboBoxModel();
    DefaultComboBoxModel modelocombo1 = new DefaultComboBoxModel();
    
    
    
    DefaultComboBoxModel modelocombo2 = new DefaultComboBoxModel();
    
    public void llenarComboPro(){
      
        try {
            erp.OpenCon("ERP", "erp");
            erp.stn= (Statement) erp.con.createStatement();
            
            erp.rs= erp.stn.executeQuery("select idproducto, nombre from productos where estatus='A'" );
            
            modelocombo2.addElement("Selecione un producto");
            
            cbxproveedor.setModel(modelocombo2);
            while (erp.rs.next()){
                String IDPRESENTACION=String.valueOf( erp.rs.getObject("idproducto"));
                String Nombre=(String) erp.rs.getObject("nombre");
            

                modelocombo2.addElement(IDPRESENTACION +" "+ Nombre );
                cbxproveedor.setModel(modelocombo2);
            }
        
        }catch(SQLException ex){
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
  File  blob ;
  
          FileInputStream  in;
    
    private void btnAgregarPerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPerceActionPerformed
        
    
        
        
        
        
        
        
        
        
        
        
        
        
      
        
if(!txfnombreC.getText().isEmpty()&&
        cbxproveedor.getSelectedIndex()> 0&& lblfoto.getIcon()!=null){


        
   
    String a2 = null,
            b=String.valueOf(cbxproveedor.getSelectedItem()).replace(" ", "%"),b2=null;
    
  
    
    for (int i = 0; i < b.length(); i++) {
        if(b.charAt(i)=='%'){
         b2=String.valueOf(cbxproveedor.getSelectedItem()).substring(0, i);
         break;
        }
    }
        
        
        
        try {
      
  







          
    String sql = "INSERT INTO imagenesproducto VALUES(ERP.sip.nextval,"
             
       + " ?, ?, ?, ?)";
            
         erp.OpenCon("ERP", "erp");
         String array[]=new String[5];
         array[0]=this.txfnombreC.getText();
         array[1]=b2;
         
     erp.SQLima(sql,array ,blob, in, ruta);
      
       
    
 
            
          


        } catch (Exception e) {
        
    }
    
   

   
  
      
   
}else{
    JOptionPane.showMessageDialog(null, "ingrese todos los campos");
}

    }//GEN-LAST:event_btnAgregarPerceActionPerformed

    private void txfnombreCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfnombreCKeyTyped
 
// ignorar el evento de teclado        // TODO add your handling code here:
    }//GEN-LAST:event_txfnombreCKeyTyped

    private void txfnombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfnombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfnombreCActionPerformed

    private void cbxproveedorHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cbxproveedorHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorHierarchyChanged

    private void cbxproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxproveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorActionPerformed

    private void cbxproveedorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxproveedorPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorPropertyChange

    private void cbxproveedorVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cbxproveedorVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorVetoableChange

    String ruta;
    private void btnSeImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeImActionPerformed
JFileChooser fc = new JFileChooser();
       
 fc.setMultiSelectionEnabled(true);
      
  fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
     
   FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.PNG", "png", "*.JPG", "jpg");
    
    fc.setFileFilter(filtro);
        
    
    Component contentPane = null;
    
    int seleccion=fc.showOpenDialog(contentPane);
        
     
   if(seleccion==JFileChooser.APPROVE_OPTION){
         
   File ficheros = ficheros = fc.getSelectedFile();
            
ruta = ficheros.getPath();
       
     System.out.println(ruta);
        
    ImageIcon imagen = new ImageIcon(ruta);
     
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(this.lblfoto.getWidth(),
        
            this.lblfoto.getHeight(), Image.SCALE_DEFAULT));
          
  this.lblfoto.setIcon(icono);
        
    this.repaint();
   }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnSeImActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_ADD_CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_ADD_CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_ADD_CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_ADD_CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_ADD_CP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPerce;
    private javax.swing.JButton btnLimpiarPerce;
    private javax.swing.JButton btnSeIm;
    private javax.swing.JComboBox cbxproveedor;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JTextField txfnombreC;
    // End of variables declaration//GEN-END:variables
}
