/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package C_Frames;

import C_Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class C_Laboratorios extends javax.swing.JPanel {

    /**
     * Creates new form Estados2
     */
    Conexion erp;
    public C_Laboratorios() {
        initComponents();
        erp = new Conexion();
    }
 
    
    private String[] getColumnas(){
          String columna[]=new String[]{"ID ESTADO", "NOMBRE ",  "SIGLAS", "ESTATUS"};
          return columna;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        C_Laboratorios_txfLab = new javax.swing.JTextField();
        btnConsEstados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLab = new javax.swing.JTable();
        btnElimEstados = new javax.swing.JButton();
        btnAgrEstados = new javax.swing.JButton();
        btnEditarEstados = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 251, 251));
        setForeground(new java.awt.Color(254, 254, 254));

        C_Laboratorios_txfLab.setBackground(new java.awt.Color(254, 254, 254));
        C_Laboratorios_txfLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_Laboratorios_txfLabActionPerformed(evt);
            }
        });

        btnConsEstados.setBackground(new java.awt.Color(254, 254, 254));
        btnConsEstados.setForeground(new java.awt.Color(254, 254, 254));
        btnConsEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-buscar.png"))); // NOI18N
        btnConsEstados.setBorderPainted(false);
        btnConsEstados.setContentAreaFilled(false);
        btnConsEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsEstadosActionPerformed(evt);
            }
        });

        tblLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Laboratorio", "Nombre", "Origen", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLab.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLab.setShowHorizontalLines(false);
        tblLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLab);

        btnElimEstados.setBackground(new java.awt.Color(254, 254, 254));
        btnElimEstados.setForeground(new java.awt.Color(254, 254, 254));
        btnElimEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borar1-icon.png"))); // NOI18N
        btnElimEstados.setBorderPainted(false);
        btnElimEstados.setContentAreaFilled(false);
        btnElimEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimEstadosActionPerformed(evt);
            }
        });

        btnAgrEstados.setBackground(new java.awt.Color(254, 254, 254));
        btnAgrEstados.setForeground(new java.awt.Color(254, 254, 254));
        btnAgrEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        btnAgrEstados.setToolTipText("");
        btnAgrEstados.setBorderPainted(false);
        btnAgrEstados.setContentAreaFilled(false);
        btnAgrEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrEstadosActionPerformed(evt);
            }
        });

        btnEditarEstados.setBackground(new java.awt.Color(254, 254, 254));
        btnEditarEstados.setForeground(new java.awt.Color(254, 254, 254));
        btnEditarEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-cambiar.png"))); // NOI18N
        btnEditarEstados.setBorderPainted(false);
        btnEditarEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEstadosActionPerformed(evt);
            }
        });

        btnRefrescar.setBackground(new java.awt.Color(254, 254, 254));
        btnRefrescar.setForeground(new java.awt.Color(254, 254, 254));
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh_icon.png"))); // NOI18N
        btnRefrescar.setBorderPainted(false);
        btnRefrescar.setContentAreaFilled(false);
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("BUSCAR POR NOMBRE DEL LABORATORIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(C_Laboratorios_txfLab, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsEstados)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarEstados)
                        .addGap(51, 51, 51)
                        .addComponent(btnElimEstados)
                        .addGap(41, 41, 41)))
                .addComponent(btnAgrEstados)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConsEstados))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C_Laboratorios_txfLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefrescar)
                    .addComponent(btnElimEstados)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnAgrEstados))
                    .addComponent(btnEditarEstados, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void borrarTabla(JTable tab) {
        try {
            DefaultTableModel tabT = (DefaultTableModel) tab.getModel();
            for (int i = tabT.getRowCount() - 1; i > -1; i--) {
                tabT.removeRow(i);
            }
        } catch (Exception e) {
       
        }
    }
    private void btnConsEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsEstadosActionPerformed
        borrarTabla(tblLab);
        erp.OpenCon("ERP", "erp");
        erp.Lab_Search(C_Laboratorios_txfLab.getText(), tblLab);
    }//GEN-LAST:event_btnConsEstadosActionPerformed

    private void btnElimEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimEstadosActionPerformed
        int ID = 0;
        int con=tblLab.getSelectedRow();
        
        if (con>=0){
            String es= String.valueOf(tblLab.getValueAt(con,3));
            if(es.equals("A"))
            {
            ID = Integer.parseInt(tblLab.getValueAt(tblLab.getSelectedRow(),0)+"");
            if(JOptionPane.showConfirmDialog (null, "Desea Eliminar","Informacion",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
               erp.SQL("update laboratorios set estatus='B' where idlaboratorio ="+ID);
            }
            }else{
                JOptionPane.showMessageDialog(null,"Seleccione un producto con estatus A","Error" ,JOptionPane.INFORMATION_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(null,"Seleccione un renglon","Error" ,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnElimEstadosActionPerformed

    private void btnAgrEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrEstadosActionPerformed
        C_ADD_Laboratorios edg=new C_ADD_Laboratorios();
        edg.setLocationRelativeTo(edg);
        edg.setVisible(true);

    }//GEN-LAST:event_btnAgrEstadosActionPerformed

    private void btnEditarEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstadosActionPerformed
        String a=(String) tblLab.getValueAt(tblLab.getSelectedRow(),0);
        String b=(String) tblLab.getValueAt(tblLab.getSelectedRow(),1);
        String c=(String) tblLab.getValueAt(tblLab.getSelectedRow(),2);
        
        C_MOD_Laboratorios lab=new C_MOD_Laboratorios();
        lab.setLocationRelativeTo(lab);
        lab.Datos(a, b, c);
        lab.setVisible(true);
        int ID = 0;
        try{
            ID = Integer.parseInt(tblLab.getValueAt(tblLab.getSelectedRow(),0)+"");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error" ,JOptionPane.INFORMATION_MESSAGE);
        }
        lab.txfIdLab.setText(ID+"");
    }//GEN-LAST:event_btnEditarEstadosActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        int ID = 0;
        int con=tblLab.getSelectedRow();
        
        if (con>=0){
            String es= String.valueOf(tblLab.getValueAt(con,3));
            if(es.equals("B"))
            {
            ID = Integer.parseInt(tblLab.getValueAt(tblLab.getSelectedRow(),0)+"");
            if(JOptionPane.showConfirmDialog (null, "Desea dar de Activar","Informacion",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
               erp.SQL("update laboratorios set estatus='A' where idlaboratorio ="+ID);
            }
            }else{
                JOptionPane.showMessageDialog(null,"Seleccione un producto con estatus B","Error" ,JOptionPane.INFORMATION_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(null,"Seleccione un renglon","Error" ,JOptionPane.INFORMATION_MESSAGE);
        }     
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void C_Laboratorios_txfLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_Laboratorios_txfLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_Laboratorios_txfLabActionPerformed

    private void tblLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLabMouseClicked
        String a=(String) tblLab.getValueAt(tblLab.getSelectedRow(),0);
        String b=(String) tblLab.getValueAt(tblLab.getSelectedRow(),1);
        String c=(String) tblLab.getValueAt(tblLab.getSelectedRow(),2);
        
                       
         if (evt.getClickCount()==2){
         C_MOD_Laboratorios lab= new C_MOD_Laboratorios();
         lab.setLocationRelativeTo(lab);
         lab.Datos(a, b, c);
         lab.setVisible(true);
         }

        
    }//GEN-LAST:event_tblLabMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_Laboratorios_txfLab;
    private javax.swing.JButton btnAgrEstados;
    private javax.swing.JButton btnConsEstados;
    private javax.swing.JButton btnEditarEstados;
    private javax.swing.JButton btnElimEstados;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblLab;
    // End of variables declaration//GEN-END:variables
}
