/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package C_Frames;

import C_Conexion.Conexion;
import static C_Conexion.Conexion.con;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 *
 * @author je_mg
 */
public class C_MOD_IMG extends javax.swing.JFrame {
Conexion erp;
String ruta="";
    /**
     * Creates new form C_MOD_IMG
     */
    public C_MOD_IMG() {
        initComponents();
        erp=new Conexion();
    }
public void Datos(String a1,String a2,String a3,String a4) throws SQLException{
txfclave.setText(a1);
txfnombreC.setText(a2);
cbxproveedor.addItem(llenar(a1)+" "+a4);
    try {
        im(a1);
    } catch (IOException ex) {
        Logger.getLogger(C_MOD_IMG.class.getName()).log(Level.SEVERE, null, ex);
    }
    txfclave.setEditable(false);
}
String llenar(String fecha){
    
        try {
            erp.OpenCon("ERP", "erp");
            erp.stn= (Statement) erp.con.createStatement();
            
            erp.rs= erp.stn.executeQuery("select idproducto from imagenesproducto where idimagen= "+fecha );

         
            while (erp.rs.next()){
                String IDPRESENTACION=String.valueOf( erp.rs.getObject("idproducto"));
            

             return IDPRESENTACION;
            }
        }catch(Exception e){
            
            }
return null;}

void im(String fecha) throws SQLException, IOException{
    
     erp.OpenCon("ERP", "erp");
     erp.con.commit();
            erp.stn= (Statement) erp.con.createStatement();
            
            erp.rs= erp.stn.executeQuery("select imagen,nobreimagen from imagenesproducto where idimagen= "+fecha );

         
            while (erp.rs.next()){
             
                    Image i=null;
          
          Blob blob = erp.rs.getBlob("imagen");
           String n = erp.rs.getString("nobreimagen");
                    
i= javax.imageio.ImageIO.read(blob.getBinaryStream());
                   
    ImageIcon imagen = new ImageIcon(i);
                 
   Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblfoto.getWidth(),
    
               lblfoto.getHeight(), 
Image.SCALE_DEFAULT));
       
             lblfoto.setIcon(icono);
                 
            }
    
    
 
                  
                 
   
                    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpiarPerce = new javax.swing.JButton();
        btnAgregarPerce = new javax.swing.JButton();
        txfnombreC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxproveedor = new javax.swing.JComboBox();
        lblfoto = new javax.swing.JLabel();
        btnSeIm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txfclave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modifica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 43, 0))); // NOI18N

        btnLimpiarPerce.setBackground(new java.awt.Color(254, 254, 254));
        btnLimpiarPerce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-cancelar.png"))); // NOI18N
        btnLimpiarPerce.setToolTipText("");
        btnLimpiarPerce.setBorderPainted(false);
        btnLimpiarPerce.setContentAreaFilled(false);
        btnLimpiarPerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPerceActionPerformed(evt);
            }
        });

        btnAgregarPerce.setBackground(new java.awt.Color(254, 254, 254));
        btnAgregarPerce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh_icon.png"))); // NOI18N
        btnAgregarPerce.setBorderPainted(false);
        btnAgregarPerce.setContentAreaFilled(false);
        btnAgregarPerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPerceActionPerformed(evt);
            }
        });

        txfnombreC.setBackground(new java.awt.Color(254, 254, 254));
        txfnombreC.setForeground(new java.awt.Color(1, 1, 1));
        txfnombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfnombreCActionPerformed(evt);
            }
        });
        txfnombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfnombreCKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("Nombre imagen");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Seleccione un proveedor");

        cbxproveedor.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                cbxproveedorHierarchyChanged(evt);
            }
        });
        cbxproveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxproveedorFocusGained(evt);
            }
        });
        cbxproveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxproveedorMouseClicked(evt);
            }
        });
        cbxproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxproveedorActionPerformed(evt);
            }
        });
        cbxproveedor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxproveedorPropertyChange(evt);
            }
        });
        cbxproveedor.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cbxproveedorVetoableChange(evt);
            }
        });

        lblfoto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "IMAGEN"));

        btnSeIm.setText("Seleciona imagen");
        btnSeIm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeImActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Clave");

        txfclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfclaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSeIm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbxproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfnombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimpiarPerce, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarPerce, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfclave, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(0, 167, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txfnombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeIm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimpiarPerce, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPerce, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarPerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPerceActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLimpiarPerceActionPerformed
  File  blob ;
  
          FileInputStream  in;
    private void btnAgregarPerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPerceActionPerformed

        erp.OpenCon("ERP", "erp");

        if(!txfnombreC.getText().isEmpty()&&
            !cbxproveedor.getSelectedItem().equals("Selecione un producto")&& lblfoto.getIcon()!=null){

            String a2 = null,
            b=String.valueOf(cbxproveedor.getSelectedItem()).replace(" ", "%"),b2=null;

            for (int i = 0; i < b.length(); i++) {
                if(b.charAt(i)=='%'){
                    b2=String.valueOf(cbxproveedor.getSelectedItem()).substring(0, i);
                    break;
                }
            }

            try {

                if(!ruta.equals("")){
                    try{

                            String sql = "UPDATE ERP.imagenesproducto "
                        
                                        + "set nobreimagen = ?,"
                        
                                + "    imagen= ?,"
                        
                                   + "    principal = ?,"
                        
                                     + "    idproducto = ?"
                        
                            + "where idimagen = ?";
                            String array[]=new String[5];
                                    array[0]=txfnombreC.getText();
                                    array[1]=b2;
                                    array[2]=txfclave.getText();
                        erp.SQLAI(sql, array, blob, in, ruta);
                        
                        
                        
                               
                        
                        

                    }catch(Exception e){

                        JOptionPane.showMessageDialog(null, "ERROR: a "+e.getMessage());

                    }

                    // erp.V = null;
                }else{
                    String sql = "update imagenesproducto "

                    + "set Nobreimagen = '"+txfnombreC.getText()+"',"+ "    principal = 'A',"

                    + " idproducto = "+b2

                    + "WHERE IDimagen = "+txfclave.getText();
                    erp.SQL(sql);

                }

            } catch (Exception e) {

            }

        }else{
            JOptionPane.showMessageDialog(null, "ingrese todos los campos");
        }
    }//GEN-LAST:event_btnAgregarPerceActionPerformed

    private void txfnombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfnombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfnombreCActionPerformed

    private void txfnombreCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfnombreCKeyTyped

        // ignorar el evento de teclado        // TODO add your handling code here:
    }//GEN-LAST:event_txfnombreCKeyTyped

    private void cbxproveedorHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cbxproveedorHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorHierarchyChanged
     DefaultComboBoxModel modelocombo = new DefaultComboBoxModel();
    
    public void llenarpro(){
        try {
            erp.OpenCon("ERP", "erp");
            erp.stn= (Statement) erp.con.createStatement();
            
            erp.rs= erp.stn.executeQuery("select IDproducto, nombre from productos where ESTATUS='A'");
            
            modelocombo.addElement("Selecione una Sucursal");
            
            cbxproveedor.setModel(modelocombo);
            while (erp.rs.next()){
                String IDPRESENTACION=String.valueOf( erp.rs.getObject("IDproducto"));
                String Nombre=(String) erp.rs.getObject("NOMBRE");

                modelocombo.addElement(IDPRESENTACION +" "+ Nombre);
                cbxproveedor.setModel(modelocombo);
            }
        
        }catch(SQLException ex){
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void cbxproveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxproveedorFocusGained
  llenarpro(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorFocusGained

    private void cbxproveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxproveedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorMouseClicked

    private void cbxproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxproveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorActionPerformed

    private void cbxproveedorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxproveedorPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorPropertyChange

    private void cbxproveedorVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cbxproveedorVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxproveedorVetoableChange

    private void btnSeImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeImActionPerformed
        JFileChooser fc = new JFileChooser();

        fc.setMultiSelectionEnabled(true);

        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.PNG", "png", "*.JPG", "jpg");

        fc.setFileFilter(filtro);

        Component contentPane = null;

        int seleccion=fc.showOpenDialog(contentPane);

        if(seleccion==JFileChooser.APPROVE_OPTION){

            File ficheros = ficheros = fc.getSelectedFile();

            ruta = ficheros.getPath();

            System.out.println(ruta);

            ImageIcon imagen = new ImageIcon(ruta);

            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(this.lblfoto.getWidth(),

                this.lblfoto.getHeight(), Image.SCALE_DEFAULT));

        this.lblfoto.setIcon(icono);

        this.repaint();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeImActionPerformed

    private void txfclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfclaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_MOD_IMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_MOD_IMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_MOD_IMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_MOD_IMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_MOD_IMG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPerce;
    private javax.swing.JButton btnLimpiarPerce;
    private javax.swing.JButton btnSeIm;
    private javax.swing.JComboBox cbxproveedor;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JTextField txfclave;
    private javax.swing.JTextField txfnombreC;
    // End of variables declaration//GEN-END:variables
}
