/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package C_Frames;

import C_Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TabableView;

/**
 *
 * @author rocker
 */
public class C_Select_Pedido extends javax.swing.JFrame {

    /**
     * Creates new form ModificarCiudades
     */
    Conexion erp;
    public C_Select_Pedido() {
        initComponents();
        erp = new Conexion();
        PanelDetalles.setEnabled(false);
         PanelDetalles.setVisible(false);
         TableDet.setEnabled(false);
         TableDet.setVisible(false);
         jScrollPane2.setEnabled(false);
         jScrollPane2.setVisible(false);
        erp.SelectP_Search(TablePed);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarDe = new javax.swing.JButton();
        idPe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label99 = new javax.swing.JLabel();
        L_IdD = new javax.swing.JLabel();
        L_CantPed = new javax.swing.JLabel();
        L_PreComp = new javax.swing.JLabel();
        L_Subtotal = new javax.swing.JLabel();
        L_CantReci = new javax.swing.JLabel();
        L_CantRh = new javax.swing.JLabel();
        L_CantAcp = new javax.swing.JLabel();
        jFrames = new javax.swing.JPanel();
        PanelPedido = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePed = new javax.swing.JTable();
        PanelDetalles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDet = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 255, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("PEDIDO SELECIONADO");

        btnAgregarDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        btnAgregarDe.setBorderPainted(false);
        btnAgregarDe.setContentAreaFilled(false);
        btnAgregarDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarDeMouseClicked(evt);
            }
        });
        btnAgregarDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDeActionPerformed(evt);
            }
        });

        idPe.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        idPe.setForeground(new java.awt.Color(1, 1, 1));
        idPe.setText("ninguno");

        jButton1.setText("Ver detalles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("ID DETALLES");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("CANT. PEDIDA");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("PRECIO COMPRA");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("SUBTOTAL");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("CANT. RECIBIDA");

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("CANT. RECHAZADA");

        label99.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        label99.setForeground(new java.awt.Color(1, 1, 1));
        label99.setText("CANT. ACEPTADA");

        L_IdD.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        L_IdD.setForeground(new java.awt.Color(1, 1, 1));
        L_IdD.setText("NA");

        L_CantPed.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        L_CantPed.setForeground(new java.awt.Color(1, 1, 1));
        L_CantPed.setText("NA");

        L_PreComp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        L_PreComp.setForeground(new java.awt.Color(1, 1, 1));
        L_PreComp.setText("NA");

        L_Subtotal.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        L_Subtotal.setForeground(new java.awt.Color(1, 1, 1));
        L_Subtotal.setText("NA");

        L_CantReci.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        L_CantReci.setForeground(new java.awt.Color(1, 1, 1));
        L_CantReci.setText("NA");

        L_CantRh.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        L_CantRh.setForeground(new java.awt.Color(1, 1, 1));
        L_CantRh.setText("NA");

        L_CantAcp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        L_CantAcp.setForeground(new java.awt.Color(1, 1, 1));
        L_CantAcp.setText("NA");

        jFrames.setMinimumSize(new java.awt.Dimension(838, 380));
        jFrames.setLayout(null);

        TablePed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPedido", "fecha Regis", "fecha Recep", "Total a pagar", "Cantidad Pagada", "Estatus", "idProveedor", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePed.setToolTipText("");
        TablePed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablePed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePed);

        javax.swing.GroupLayout PanelPedidoLayout = new javax.swing.GroupLayout(PanelPedido);
        PanelPedido.setLayout(PanelPedidoLayout);
        PanelPedidoLayout.setHorizontalGroup(
            PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        PanelPedidoLayout.setVerticalGroup(
            PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        jFrames.add(PanelPedido);
        PanelPedido.setBounds(0, 0, 830, 360);

        TableDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPed_Det", "Cant Pedida", "Precio Compra", "Subtotal", "Cant Recibida", "Cant Rechazada", "Cant Aceptada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableDet.setToolTipText("");
        TableDet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableDet.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDet);

        javax.swing.GroupLayout PanelDetallesLayout = new javax.swing.GroupLayout(PanelDetalles);
        PanelDetalles.setLayout(PanelDetallesLayout);
        PanelDetallesLayout.setHorizontalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        PanelDetallesLayout.setVerticalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        jFrames.add(PanelDetalles);
        PanelDetalles.setBounds(0, 0, 830, 340);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-salir.png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPe)
                        .addGap(552, 552, 552)
                        .addComponent(jButton1))
                    .addComponent(jFrames, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_CantPed)
                            .addComponent(L_IdD)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_CantReci)
                            .addComponent(L_Subtotal)
                            .addComponent(L_PreComp)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(label99))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_CantAcp)
                            .addComponent(L_CantRh)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarDe)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idPe))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(L_IdD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(L_CantPed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(L_PreComp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(L_Subtotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(L_CantReci))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(L_CantRh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label99)
                            .addComponent(L_CantAcp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar))
                    .addComponent(jFrames, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarDe, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarDeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDeMouseClicked

    private void btnAgregarDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDeActionPerformed
        // TODO add your handling code here:
        C_ADD_Pagos edg;
        edg = new C_ADD_Pagos();
        edg.setLocationRelativeTo(edg);
        edg.setVisible(true);
        edg.ID_Ped.setText(idPe.getText());
       
    }//GEN-LAST:event_btnAgregarDeActionPerformed
public void borrarTabla(JTable tab) {
        try {
            DefaultTableModel tabT = (DefaultTableModel) tab.getModel();
            for (int i = tabT.getRowCount() - 1; i > -1; i--) {
                tabT.removeRow(i);
            }
        } catch (Exception e) {
       
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     /*C_S_Pedido erp = new C_S_Pedido();
        erp.setSize(jFrames.getSize());
        erp.setLocation(0, 0);
        jFrames.removeAll();
        jFrames.add(erp);
        jFrames.revalidate();
        jFrames.repaint();*/
     if(jButton1.getText().equals("Ver detalles")){
         borrarTabla(TableDet);
         jButton1.setText("Ver pedidos");
         PanelPedido.setEnabled(false);
         PanelPedido.setVisible(false);
         TablePed.setVisible(false);
         TablePed.setEnabled(false);
         jScrollPane1.setEnabled(false);
         jScrollPane1.setVisible(false);
         
         PanelDetalles.setEnabled(true);
         PanelDetalles.setVisible(true);
         TableDet.setEnabled(true);
         TableDet.setVisible(true);
         jScrollPane2.setEnabled(true);
         jScrollPane2.setVisible(true);
         erp.SelectP_Detalles_Search(TableDet,Integer.parseInt(idPe.getText()));
     }else {
         borrarTabla(TablePed);
         jButton1.setText("Ver detalles");
         PanelDetalles.setEnabled(false);
         PanelDetalles.setVisible(false);
         TableDet.setEnabled(false);
         TableDet.setVisible(false);
         jScrollPane2.setEnabled(false);
         jScrollPane2.setVisible(false);
         
         PanelPedido.setEnabled(true);
         PanelPedido.setVisible(true);
         TablePed.setVisible(true);
         TablePed.setEnabled(true);
         jScrollPane1.setEnabled(true);
         jScrollPane1.setVisible(true);
         erp.SelectP_Search(TablePed);
     }
     
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablePedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePedMouseClicked
        // TODO add your handling code here:
       idPe.setText(TablePed.getValueAt(TablePed.getSelectedRow(), 0)+"");
    }//GEN-LAST:event_TablePedMouseClicked

    private void TableDetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDetMouseClicked
        // TODO add your handling code here:
        L_IdD.setText(TableDet.getValueAt(TableDet.getSelectedRow(), 0)+"");
        L_CantPed.setText(TableDet.getValueAt(TableDet.getSelectedRow(), 1)+"");
        L_PreComp.setText(TableDet.getValueAt(TableDet.getSelectedRow(), 2)+"");
        L_Subtotal.setText(TableDet.getValueAt(TableDet.getSelectedRow(), 3)+"");
        L_CantReci.setText(TableDet.getValueAt(TableDet.getSelectedRow(), 4)+"");
        L_CantRh.setText(TableDet.getValueAt(TableDet.getSelectedRow(), 5)+"");
        L_CantAcp.setText(TableDet.getValueAt(TableDet.getSelectedRow(), 6)+"");
    }//GEN-LAST:event_TableDetMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Select_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Select_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Select_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Select_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Select_Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_CantAcp;
    private javax.swing.JLabel L_CantPed;
    private javax.swing.JLabel L_CantReci;
    private javax.swing.JLabel L_CantRh;
    private javax.swing.JLabel L_IdD;
    private javax.swing.JLabel L_PreComp;
    private javax.swing.JLabel L_Subtotal;
    private javax.swing.JPanel PanelDetalles;
    private javax.swing.JPanel PanelPedido;
    public javax.swing.JTable TableDet;
    public javax.swing.JTable TablePed;
    private javax.swing.JButton btnAgregarDe;
    private javax.swing.JButton btnEliminar;
    public javax.swing.JLabel idPe;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jFrames;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label99;
    // End of variables declaration//GEN-END:variables
}
